/**
 * HomePage — landing page of the Website Audit AI tool.
 *
 * Intentionally contains no business logic.
 * Structure only: hero, feature highlights, and CTA.
 */
import { Link } from 'react-router-dom'

interface Feature {
  icon: string
  title: string
  description: string
}

const FEATURES: Feature[] = [
  {
    icon: '🔍',
    title: 'SEO Analysis',
    description: 'Deep-dive into meta tags, heading hierarchy, canonical links, and structured data.',
  },
  {
    icon: '⚡',
    title: 'Performance Audit',
    description: 'Core Web Vitals, resource sizes, render-blocking assets, and caching headers.',
  },
  {
    icon: '♿',
    title: 'Accessibility',
    description: 'WCAG 2.1 checks — colour contrast, ARIA labels, keyboard navigation, and more.',
  },
  {
    icon: '🔒',
    title: 'Security',
    description: 'SSL/TLS validation, HTTP security headers, mixed-content issues, and more.',
  },
  {
    icon: '📱',
    title: 'Mobile-Friendly',
    description: 'Viewport configuration, tap target sizes, and responsive design analysis.',
  },
  {
    icon: '🤖',
    title: 'AI Insights',
    description: 'Actionable recommendations generated by AI — prioritised by business impact.',
  },
]

export default function HomePage() {
  return (
    <div className="animate-fade-in">

      {/* ── Hero ────────────────────────────────────────────────── */}
      <section
        id="hero"
        className="relative overflow-hidden py-24 md:py-36 px-4"
      >
        {/* Decorative gradient blob */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 -z-10"
          style={{
            background:
              'radial-gradient(ellipse 60% 50% at 50% 0%, rgba(99,102,241,0.18) 0%, transparent 70%)',
          }}
        />

        <div className="max-w-4xl mx-auto text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 mb-6 px-4 py-1.5 rounded-full text-sm font-medium glass animate-fade-in"
            style={{ color: 'var(--color-accent)', animationDelay: '0.05s' }}
          >
            <span className="w-2 h-2 rounded-full animate-pulse-glow" style={{ background: 'var(--color-accent)' }} />
            AI-Powered · Real-time Results
          </div>

          {/* Headline */}
          <h1
            className="text-4xl sm:text-5xl md:text-6xl font-extrabold mb-6 leading-tight tracking-tight animate-fade-in"
            style={{ animationDelay: '0.1s' }}
          >
            Audit Any Website{' '}
            <span className="gradient-text">in Seconds</span>
          </h1>

          {/* Subheadline */}
          <p
            className="text-lg md:text-xl mb-10 max-w-2xl mx-auto animate-fade-in"
            style={{ color: 'var(--color-text-muted)', animationDelay: '0.15s' }}
          >
            Get instant, AI-driven insights on SEO, performance, accessibility,
            and security — all in one comprehensive report.
          </p>

          {/* CTAs */}
          <div
            className="flex flex-col sm:flex-row gap-4 justify-center animate-fade-in"
            style={{ animationDelay: '0.2s' }}
          >
            <Link id="hero-cta-primary" to="/audit" className="btn-primary text-base px-8 py-3">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <polyline points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
              </svg>
              Start Free Audit
            </Link>
            <a
              id="hero-cta-secondary"
              href="#features"
              className="btn-ghost text-base px-8 py-3"
            >
              Learn More
            </a>
          </div>
        </div>
      </section>

      {/* ── Features grid ───────────────────────────────────────── */}
      <section
        id="features"
        className="py-20 px-4"
        aria-labelledby="features-heading"
      >
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-14">
            <h2
              id="features-heading"
              className="text-3xl md:text-4xl font-bold mb-4"
            >
              Everything You Need to{' '}
              <span className="gradient-text">Win Online</span>
            </h2>
            <p className="text-base md:text-lg max-w-xl mx-auto" style={{ color: 'var(--color-text-muted)' }}>
              Six powerful audit categories — one elegant report.
            </p>
          </div>

          <ul
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6"
            role="list"
            aria-label="Feature list"
          >
            {FEATURES.map((feature, index) => (
              <li
                key={feature.title}
                id={`feature-card-${index}`}
                className="card animate-fade-in"
                style={{ animationDelay: `${0.05 * index}s` }}
              >
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl mb-4"
                  style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.2)' }}
                  aria-hidden="true"
                >
                  {feature.icon}
                </div>
                <h3 className="text-lg font-semibold mb-2" style={{ color: 'var(--color-text-primary)' }}>
                  {feature.title}
                </h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--color-text-muted)' }}>
                  {feature.description}
                </p>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── Bottom CTA band ──────────────────────────────────────── */}
      <section
        id="cta-band"
        className="py-20 px-4"
        aria-labelledby="cta-band-heading"
      >
        <div
          className="max-w-3xl mx-auto text-center card glow"
          style={{
            background: 'linear-gradient(135deg, rgba(99,102,241,0.15) 0%, rgba(168,85,247,0.1) 100%)',
            border: '1px solid rgba(99,102,241,0.3)',
          }}
        >
          <h2
            id="cta-band-heading"
            className="text-3xl font-bold mb-4"
          >
            Ready to boost your website?
          </h2>
          <p className="mb-8 text-lg" style={{ color: 'var(--color-text-muted)' }}>
            Enter your URL and get a full report in under 30 seconds.
          </p>
          <Link id="cta-band-link" to="/audit" className="btn-primary text-base px-10 py-3">
            Run Your First Audit →
          </Link>
        </div>
      </section>

    </div>
  )
}
